# @package _group_
name: train

learning_rate: 0.001
temp_learning_rate: 0.0001  # Learning rate for the temperature only
momentum: 0
weight_decay: 0
nesterov: False

# Training loop
epochs: 1000
patience: 35
